version: '3.3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '123'
    ports:
      - '5432:5432'
    volumes:
      - my-db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  my-db:
